library(shiny)
library(dplyr)
library(ggplot2)
library(stats)
library(snakecase)

source('./src/data_paths.R')

choro_inputs = read.csv(paste(new_data, 'choropleth_inputs.csv', sep = ''),
                        stringsAsFactors = FALSE)
choro_inputs$ZCTA = as.character(choro_inputs$ZCTA)
df = choro_inputs %>% 
  distinct(ZCTA, .keep_all = TRUE)

# Uses dataframe generated by generate_choro_df to plot desired outcomes
build_choropleth <- function(choro_df, var_label, pretty_label,
                             min_color = 'lightgrey', max_color = 'darkblue',
                             show_title = F){
  if(show_title){
    new_title = sprintf('%s by zip code', pretty_label)
  }else{
    new_title = ''
  }
  
  p = ggplot() + 
    geom_polygon(data=choro_df %>% filter(!is.na(.data[[var_label]])), 
                 aes(x=long, y=lat, group=group, fill = .data[[var_label]]),
                 color = 'white', size = 0.2) +
    scale_fill_gradient(low = min_color, high = max_color, 
                        guide = 
                          guide_colorbar(
                            title = pretty_label,order = 1,reverse = F
                          )
    )+
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank()) +
    labs(title=new_title,
         x ="", y = "")
  
  return(p)
}


# Define UI for app that draws a histogram ----
ui <- fluidPage(
  
  # App title ----
  titlePanel("COVID-19 in NYC: Comparisons with Census Demographic Data"),
  br(),
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      h4(selectInput(inputId = "outcome_var",
                    label = "COVID-19 outcome:",
                    c('Percent Positive COVID Tests' = 'PERCENT_POSITIVE',
                      "Case rate per 100,000" = 'COVID_CASE_RATE',
                      'Death rate per 100,000' = 'COVID_DEATH_RATE'),
                  selected = 'Percent Positive COVID Tests')),
      h4(selectInput(inputId = 'demo_var',
                  label = "Census demographic variable:",
                  c("Median income" = 'median_income',
                    'Median rent' = 'median_rent',
                    'Percent non-citizens' = 'percent_non_citizens',
                    'Percent with disability' = 'percent_with_disability',
                    'Percent White' = 'percent_white',
                    'Percent Black' = 'percent_black',
                    'Percent Asian' = 'percent_asian',
                    'Percent Hispanic' = 'percent_hispanic_latino',
                    'Percent uninsured' = 'percent_uninsured',
                    'Percent receiving public assistance' = 'percent_receiving_public_assistance',
                    'High school completion rate' = 'high_school_completion',
                    'Percent working in managment, arts, sciences' = 'percent_in_mgmt_art_sci',
                    'Poverty rate' = 'poverty_rate',
                    'Percent spending >=35% of income on rent' = 'percent_spending_35_percent_rent',
                    'Percent with disability' = 'percent_with_disability'),
                  selected = 'Median income')),
      h4('Plot options: '),
      checkboxInput(inputId = 'show_by_borough',
                    label = h4('Show color coding for boroughs?'),
                    value = TRUE),
      checkboxInput(inputId = 'show_reg_line',
                       label = h4('Show linear relationship between variables?'),
                       value = TRUE),
      br(),
      h5('Demographic data are sourced from the US Census American Community Survey 2013-2018 (www.census.gov/programs-surveys/acs)',
         align = 'center'),
      h5('COVID-19 data are sourced from the NYC Health Dept (github.com/nychealth/coronavirus-data) and aggregated over all time',
         align = 'center')
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      fluidRow(
        column(6,
               h4(textOutput(outputId = "cov_pretty")),
               plotOutput(outputId = "cov_plot")
        ),
        column(6,
               h4(textOutput(outputId = "demo_pretty")),
               plotOutput(outputId = "census_plot")
        )
      ),
      br(),
      hr(),
      h4(textOutput(outputId = 'correlation_plot_head')),
      plotOutput(outputId = "correlation_plot"),
      br(),
      h5('All data are represented at the ZIP code or modified ZIP code level', 
         align = 'center'),
      h5('Last updated: 20 May 2020', align = 'center'),
      h5('The code for this app is available on Github: https://github.com/silverer/covid_nyc_map'),
      br(),
      br()
    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  get_corr_vars <- reactive({
    vars = df %>% 
      select(c(input$demo_var, input$outcome_var,
               Borough))
    colnames(vars) = c('x', 'y', 'Borough')
    vars
  })
  
  get_pretty_labels <- reactive({
    if(grepl('assistance', input$demo_var)){
      lab1 = 'Percent receiving\npublic assistance'
    }else if(grepl('hispanic', input$demo_var)){
      lab1 = 'Percent Hispanic/\nLatino'
    }else if(grepl('black', input$demo_var)){
      lab1 = 'Percent Black'
    }else if(grepl('mgmt', input$demo_var)){
      lab1 = 'Percent in\nmgmt, arts, sci'
    }else if(grepl('disability', input$demo_var)){
      lab1 = 'Percent with\ndisability'
    }else if(grepl('asian', input$demo_var)){
      lab1 = 'Percent Asian'
    }else if(grepl('spending', input$demo_var)){
      lab1 = 'Percent spending >=35%\nof income on rent'
    }else if(grepl('citizen', input$demo_var)){
      lab1 = 'Percent non-citizens'
    }else{
      lab1 = to_sentence_case(input$demo_var)
    }
    
    if(grepl('RATE', input$outcome_var)){
      lab2 = to_sentence_case(input$outcome_var)
      lab2 = paste(lab2, '\nper 100,000', sep = '')
    }else if(grepl('PERCENT', input$outcome_var)){
      lab2 = "Percent Positive\nCovid Tests"
    }else{
      lab2 = to_sentence_case(input$outcome_var)
    }
    
    lab2 = gsub("Covid", "COVID", lab2)
    
    labs = c(lab1, lab2)
    labs
  })
  
  get_choro_df <- reactive({
    temp = df %>% 
      select(c(input$demo_var, input$outcome_var,
               ZCTA)) 
    temp
  })
  
  output$demo_pretty <- renderText({
    pretty = get_pretty_labels()
    paste(pretty[1])
  })
  
  output$cov_pretty <- renderText({
    pretty = get_pretty_labels()
    paste(pretty[2])
  })
  
  output$correlation_plot_head <- renderText({
    labs = get_pretty_labels()
    paste(sprintf('Correlation Between %s and %s', 
                  labs[2], labs[1]))
  })
  
  output$correlation_plot <- renderPlot({
    temp = get_corr_vars()
    plot_labels = get_pretty_labels()
    temp = temp %>% 
      filter(!is.na(x) & !is.na(y))
    if(input$show_by_borough==TRUE){
      if(input$show_reg_line==TRUE){
        p = ggplot(temp, aes(x, y))+
          geom_point(aes(color=Borough)) +
          geom_smooth(method = 'lm', se = FALSE, formula = y ~ x) +
          labs(x = plot_labels[1], y = plot_labels[2])+
          theme(text = element_text(size = 20))
      }else{
        p = ggplot(temp, aes(x, y, color=Borough))+
          geom_point() +
          labs(x = plot_labels[1], y = plot_labels[2])+
          theme(text = element_text(size = 20))
      }
      
    }else{
      p = ggplot(temp, aes(x, y))+
        geom_point() +
        labs(x = plot_labels[1], y = plot_labels[2]) +
        theme(text = element_text(size = 20))
      if(input$show_reg_line){
        p = p + geom_smooth(method="lm", se=FALSE, formula = y ~ x)
      }
    }
    
    p
  })
  
  output$census_plot <- renderPlot({
    choro_inputs
    temp = get_choro_df()
    labs = get_pretty_labels()
    p = build_choropleth(choro_inputs, input$demo_var,
                         labs[1])
    p
  })
  
  output$cov_plot <- renderPlot({
    choro_inputs
    temp = get_choro_df()
    labs = get_pretty_labels()
    p = build_choropleth(choro_inputs, input$outcome_var,
                         labs[2])
    p
  })
  
}

shinyApp(ui, server)