library(shiny)
library(dplyr)
library(ggplot2)
library(stats)
library(plotly)
library(Hmisc)
library(stringr)
library(data.table)

source('./data_paths.R')

#################################
# Read in geospatial data
#################################
choro_inputs = read.csv(paste(new_data, choro_fname, sep = ''),
                        stringsAsFactors = FALSE)
choro_inputs$ZCTA = as.character(choro_inputs$ZCTA)
df = choro_inputs %>% 
  distinct(ZCTA, .keep_all = TRUE)

#Prep formatted geospatial dataframe 
pretty_columns = read.csv(paste(new_data, 'pretty_column_names.csv', sep = ''),
                          stringsAsFactors = FALSE)
pretty_columns = pretty_columns %>% 
  filter(!is.na(split_word))
pretty_columns$l2[pretty_columns$l2 == ''] = ' '
pretty_columns = pretty_columns %>% 
  mutate(formatted_name = paste(l1, l2, sep = "\n"),
         formatted_name = str_trim(formatted_name, side = 'both'),
         format_1l = paste(l1, l2, sep = ' '),
         format_1l = str_trim(format_1l, side = 'both'))

#plot_names is used to rename the choro_inputs columns
plot_names = as.vector(pretty_columns$original_name)
names(plot_names) = as.vector(pretty_columns$format_1l)
#rev_names supports plotting with pretty labels
rev_names = as.vector(pretty_columns$format_1l)
names(rev_names) = as.vector(pretty_columns$original_name)
#Create df with formatted column names
pretty_choro_inputs = choro_inputs %>% 
  rename(all_of(plot_names))

#################################
# Read in temporal data
#################################
tests = read.csv(paste(nyc_data, 'tests.csv', sep = ''),
                 stringsAsFactors = F)

pretty_tests = tests %>% 
  mutate(Date = as.Date(DATE, format='%m/%d/%Y'),
         `Percent positive tests` = as.integer(PERCENT_POSITIVE*100),
         `Total tests` = as.double(TOTAL_TESTS),
         `Positive tests` = as.double(POSITIVE_TESTS)) %>% 
  select(-c(PERCENT_POSITIVE_3DAYS_AGG, POSITIVE_TESTS,
            TOTAL_TESTS, PERCENT_POSITIVE, DATE))

deaths <- read.csv(paste(nyc_data, 'deaths/probable-confirmed-dod.csv', sep = ''),
                   stringsAsFactors = F)
deaths <- deaths %>% 
  mutate(Date = as.Date(DATE_OF_DEATH, format='%m/%d/%Y'),
         `Total deaths` = as.double(CONFIRMED_COUNT + PROBABLE_COUNT),
         `Probable deaths` = as.double(PROBABLE_COUNT),
         `Confirmed deaths` = as.double(CONFIRMED_COUNT)) %>% 
  select(-c(DATE_OF_DEATH, CONFIRMED_COUNT, PROBABLE_COUNT))

daily <- dplyr::left_join(pretty_tests, deaths, by = "Date")

tests_melted <- melt(data.table(daily %>% 
                                  mutate(`Percent positive tests` = as.character(`Percent positive tests`),
                                         `Percent positive tests` = paste(`Percent positive tests`, 
                                                                          '%', sep = '')) %>% 
                                  select(Date, `Total tests`, `Positive tests`,
                                         `Percent positive tests`, `Total deaths`,
                                         `Confirmed deaths`, `Probable deaths`)), 
                     id.vars = c('Date', 'Percent positive tests', 'Total deaths'))



#################################
# Define geospatial plotting fxns
#################################
# Uses dataframe generated by generate_choro_df to plot desired outcomes
build_choropleth <- function(choro_df, var_label, pretty_label,
                             min_color = 'lightgrey', max_color = 'darkblue',
                             show_title = F){
  if(show_title){
    new_title = pretty_label
  }else{
    new_title = ''
  }
  choro_df = choro_df %>% 
    filter(!is.na(!!var_label)) 
  
  p = ggplot(data=choro_df,
             aes(x = long, y = lat, label = ZCTA)) + 
    geom_polygon(data=choro_df, 
                 aes(x=long, y=lat, group=group,
                     fill = .data[[var_label]]),
                 color = 'white', size = 0.2) +
    scale_fill_gradient(low = min_color, high = max_color, 
                        guide = 
                          guide_colorbar(
                            title = pretty_label,order = 1,reverse = F
                          )
    )+
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank()) +
    labs(title=new_title,
         x ="", y = "")
  
  return(p)
}

#Plot a scatter plot with or without extra summary/grouping features
build_corr_plot <- function(df, xvar, yvar,
                            show_reg, show_boro){
  
  plot_df = df %>% 
    dplyr::filter(!is.na(.data[[xvar]]) & !is.na(.data[[yvar]])) %>% 
    dplyr::distinct(ZCTA, .keep_all = TRUE)
  
  if(show_boro==TRUE){
    p = ggplot(plot_df, aes(.data[[xvar]], .data[[yvar]], label = ZCTA))+
      geom_point(aes(color=Borough)) +
      labs(x = xvar, y = yvar)
  }else{
    p = ggplot(plot_df, aes(.data[[xvar]], .data[[yvar]], label = ZCTA))+
      geom_point()
  }
  if(show_reg==TRUE){
    p = p +  geom_smooth(method = 'lm', se = FALSE, formula = y ~ x)
  }
  p = p + theme(panel.background = element_blank(),
                axis.line = element_line(colour = "black"),
                text = element_text(size = 16),
                axis.text.x = element_text(size = 14),
                axis.text.y = element_text(size = 14),
                axis.title = element_text(size = 14),
                legend.title = element_blank())
  return(p)
}

get_correlations <- function(df){
  merged.rcorr = rcorr(as.matrix(df))
  merged.coeff = merged.rcorr$r
  merged.p = merged.rcorr$P
  if(merged.coeff[1,1]!=1.0){
    r_val = merged.coeff[1,1]
    p_val = merged.p[1,1]
  }else{
    r_val = merged.coeff[1,2]
    p_val = merged.p[1,2]
  }
  return(c(r_val, p_val))
}

#################################
# Define temporal plotting fxns
#################################

build_time_plot <- function(df, var_label, tooltip_var){
  temp = ggplot(data = df, aes(x = Date, y = .data[[var_label]],
                               label = .data[[tooltip_var]]))+
    geom_bar(stat = 'identity', fill = 'turquoise', color = 'white')+
    labs(title= paste(var_label, 'per day'),
         x ="Date", y = var_label)+
    theme(panel.background = element_blank(),
          axis.line = element_line(colour = "black"),
          text = element_text(size = 14),
          axis.text.x = element_text(size = 12),
          axis.text.y = element_text(size = 12),
          axis.title = element_text(size = 12),
          legend.title = element_blank())
  return(temp)
}

build_combined_time_plot <- function(melted_df, plot_type = 'tests'){
  if(plot_type == 'tests'){
    vars = c('Total tests', 'Positive tests')
    temp_df = melted_df %>% 
      filter(variable %in% vars)
    temp = ggplot(data = as.data.frame(temp_df), aes(x = Date, y = value, 
                                                     label = `Percent positive tests`, fill = variable,
                                                     text = paste(variable, value, sep = ': ')))
    title_text='COVID Testing Over Time'
  }else{
    vars = c('Confirmed deaths', 'Probable deaths')
    temp_df = melted_df %>% 
      filter(variable %in% vars)
    temp_df[is.na(temp_df)] = 0
    temp = ggplot(data = as.data.frame(temp_df), aes(x = Date, y = value, 
                                                     label = `Total deaths`, fill = variable,
                                                     text = paste(variable, value, sep = ': ')))
    title_text = 'COVID Deaths Over Time'
  }
  temp = temp +
    geom_bar(stat = 'identity', position = 'stack')+
    scale_fill_discrete(labels = vars)+
    labs(title=title_text,
         x ="Date", y = "Count")+
    theme(panel.background = element_blank(),
          axis.line = element_line(colour = "white"),
          text = element_text(size = 14),
          axis.text.x = element_text(size = 12),
          axis.text.y = element_text(size = 12),
          axis.title = element_text(size = 12),
          legend.title = element_blank())
  return(temp)
}

#################################
# Define UI for app
#################################
ui <- fluidPage(
  
  # App title ----
  titlePanel("COVID-19 in NYC: Comparisons with Census Demographic Data"),
  br(),
  br(),
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    # Sidebar panel for inputs ----
    sidebarPanel(
      h4(selectInput(inputId = "outcome_var",
                     label = "COVID-19 outcome:",
                     c('Percent Positive COVID Tests' = 'PERCENT_POSITIVE',
                       "Case rate per 100,000" = 'COVID_CASE_RATE',
                       'Death rate per 100,000' = 'COVID_DEATH_RATE'),
                     selected = 'Percent Positive COVID Tests')),
      h4(selectInput(inputId = 'demo_var',
                     label = "Census demographic variable:",
                     c("Median income" = 'median_income',
                       'Median rent' = 'median_rent',
                       'Percent with disability' = 'percent_with_disability',
                       'Percent white' = 'percent_white',
                       'Percent Black' = 'percent_black',
                       'Percent Asian' = 'percent_asian',
                       'Percent Hispanic/Latino' = 'percent_hispanic_latino',
                       'Percent uninsured' = 'percent_uninsured',
                       'Percent receiving public assistance' = 'percent_receiving_public_assistance',
                       'High school completion rate' = 'high_school_completion',
                       'College completion rate' = 'college_graduates',
                       'Percent working in managment, arts, sciences' = 'percent_in_mgmt_art_sci',
                       'Poverty rate' = 'poverty_rate',
                       'Percent spending >=35% of income on rent' = 'percent_spending_35_percent_rent'),
                     selected = 'Median income')),
      h4('Plot options: '),
      checkboxInput(inputId = 'show_by_borough',
                    label = h4('Show color coding for boroughs?'),
                    value = TRUE),
      checkboxInput(inputId = 'show_reg_line',
                    label = h4('Show linear relationship between variables?'),
                    value = TRUE),
      br(),
      h5(uiOutput("acs_ref"),
         align = 'center'),
      h5(uiOutput("covid_github_ref"),
         align = 'center')
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      tags$style(type="text/css", "
                           #loadmessage {
                             position: fixed;
                             top: 200px;
                             left: 500px;
                             width: 50%;
                             padding: 5px 0px 5px 0px;
                             text-align: left;
                             font-weight: bold;
                             font-size: 200%;
                             color: #000000;
                             z-index: 105;
                           }
                          "),
      conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                       tags$div("Loading...",id="loadmessage")),
      tabsetPanel(type = "tabs",
                  tabPanel("Geospatial Plots",
                           br(),
                           
                           fluidRow(
                             
                             column(6,
                                    h4(textOutput(outputId = "cov_pretty")),
                                    plotlyOutput(outputId = "cov_plot")
                             ),
                             column(6,
                                    h4(textOutput(outputId = "demo_pretty")),
                                    plotlyOutput(outputId = "census_plot")
                             ),
                           ),
                           h5("Note: ZCTA stands for Zip Code Tabulation Area. For more detailed data, hover your mouse over the charts."),
                           hr(),
                           h4(textOutput(outputId = 'correlation_plot_head')),
                           h5(uiOutput("stats_ref")),
                           plotlyOutput(outputId = "correlation_plot"),
                           br(),
                           h5('All data are represented at the ZIP code or modified ZIP code level', 
                              align = 'center')
                  ),
                  tabPanel("Temporal Plots",
                           h4('These plots show COVID-19 testing and mortality data for New York City over time.',
                              align = 'center'),
                           h4('Hover your mouse over the plot to see more detailed data.',
                              align = 'center'),
                           br(),
                           plotlyOutput(outputId = "big_time_test_plot"),
                           br(),
                           plotlyOutput(outputId = "big_time_death_plot"),
                           br(),
                           hr(),
                           br(),
                           fluidRow(
                             column(6,
                                    plotlyOutput(outputId = "perc_pos_time")
                             ),
                             column(6,
                                    plotlyOutput(outputId = "num_tests_time")
                             ),
                           ),
                           br()
                  ),
                  tabPanel("About", 
                           br(),
                           h3("About the Project & Other Resources"),
                           br(),
                           
                           h5(uiOutput('context_text')),
                           tags$style("#context_text{font-size: 20px}"),
                           br(),
                           hr(),
                           h3("About the Developer"),
                           br(),
                           h5(uiOutput('about_me')),
                           tags$style("#about_me{font-size: 20px}"),
                           br()
                  )
      ),
      br(),
      h5('Last updated: 05 June 2020', 
         align = 'center'),
      h5(uiOutput('app_github_ref'),
         align = 'center'),
      br(),
      br()
    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  get_corr_vars <- reactive({
    vars = df %>% 
      select(c(input$demo_var, input$outcome_var,
               Borough))
    colnames(vars) = c('x', 'y', 'Borough')
    vars
  })
  
  get_pretty_labels <- reactive({
    lab1 = pretty_columns %>% filter(original_name == input$demo_var)
    rownames(lab1) = c(1)
    lab1 = lab1$formatted_name[1]
    lab2 = pretty_columns %>% filter(original_name == input$outcome_var)
    rownames(lab2) = c(1)
    lab2 = lab2$formatted_name[1]
    labs = c(lab1, lab2)
    labs
  })
  
  output$demo_pretty <- renderText({
    pretty = get_pretty_labels()
    paste(pretty[1])
  })
  
  output$cov_pretty <- renderText({
    pretty = get_pretty_labels()
    paste(pretty[2])
  })
  
  output$correlation_plot_head <- renderText({
    labs = get_pretty_labels()
    paste(sprintf('Correlation Between %s and %s', 
                  labs[2], labs[1]))
  })
  
  
  stats_url = a("What does this mean?",
                href = "https://statistics.laerd.com/statistical-guides/pearson-correlation-coefficient-statistical-guide.php")
  output$stats_ref <- renderUI({
    temp = df %>% 
      select(-c(ZCTA)) %>% 
      select(c(input$demo_var, input$outcome_var))
    
    corr_vals = get_correlations(temp)
    if(corr_vals[2]<0.001){
      pval = '< 0.001'
    }else{
      pval = sprintf("= %s", round(corr_vals[2], 3))
    }
    new_str = sprintf("Pearson's r = %s, p-value %s. ",
                      as.character(round(corr_vals[1], 2)),
                      pval)
    tagList(new_str, stats_url)
  })
  
  github_url <- a("on Github", href="https://github.com/silverer/covid_nyc_map/")
  output$app_github_ref <- renderUI({
    tagList("The code for this app is available ", github_url)
  })
  
  acs_url <- a("American Community Survey 2014-2018",
               href="https://www.census.gov/programs-surveys/acs/")
  output$acs_ref <- renderUI({
    tagList("Demographic data are sourced from the US Census ", acs_url)
  })
  covid_url = a("NYC Health Dept",
                href = "https://www.github.com/nychealth/coronavirus-data")
  output$covid_github_ref <- renderUI({
    tagList("COVID-19 data are sourced from the ", covid_url, " and aggregated over all time")
  })
  
  output$correlation_plot <- renderPlotly({
    p = build_corr_plot(pretty_choro_inputs, rev_names[input$demo_var],
                        rev_names[input$outcome_var], 
                        show_reg = input$show_reg_line,
                        show_boro = input$show_by_borough)
    ggplotly(p)
  })
  
  
  output$census_plot <- renderPlotly({
    labs = get_pretty_labels()
    p = build_choropleth(pretty_choro_inputs, rev_names[input$demo_var],
                         labs[1])
    ggplotly(p)
  })
  
  output$cov_plot <- renderPlotly({
    labs = get_pretty_labels()
    p = build_choropleth(pretty_choro_inputs, rev_names[input$outcome_var],
                         labs[2])
    ggplotly(p)
  })
  
  output$perc_pos_time <- renderPlotly({
    p = build_time_plot(pretty_tests, 'Percent positive tests', 'Total tests')
    ggplotly(p)
  })
  
  output$num_pos_time <- renderPlotly({
    p = build_time_plot(pretty_tests, 'Positive tests', 'Total tests')
    ggplotly(p)
  })
  
  output$num_tests_time <- renderPlotly({
    p = build_time_plot(pretty_tests, 'Total tests', 'Percent positive tests')
    ggplotly(p)
  })
  
  output$big_time_test_plot <- renderPlotly({
    p = build_combined_time_plot(tests_melted)
    ggplotly(p, tooltip = c("text", "Date", "label"))
  })
  
  output$big_time_death_plot <- renderPlotly({
    p = build_combined_time_plot(tests_melted, plot_type = 'deaths')
    ggplotly(p, tooltip = c("text", "Date", "label"))
  })
  
  nyt_url <- a("New York Times",
               href="https://www.nytimes.com/2020/05/18/nyregion/coronavirus-deaths-nyc.html")
  nejm_url <- a("New England Journal of Medicine",
                href = "https://www.nejm.org/doi/full/10.1056/NEJMp2012910")
  harv_paper_url <- a("Dr. Jarvis T. Chen and Dr. Nancy Krieger (2020)",
                      href = "https://cdn1.sph.harvard.edu/wp-content/uploads/sites/1266/2020/04/HCPDS_Volume-19_No_1_20_covid19_RevealingUnequalBurden_HCPDSWorkingPaper_04212020-1.pdf")
  
  hsph_url <- a("Harvard School of Public Health.",
                href = "https://www.hsph.harvard.edu/thegeocodingproject/covid-19-resources/")
  
  output$context_text <- renderUI({
    intro = paste('The purpose of this project is to help visualize disparities in COVID-19 outcomes', 
                  ' by demographic and socioeconomic characteristics of neighborhoods in New York City.',
                  sep = ' ')
    temp_pre_nyt = " These disparities have been reported by the "
    temp_pre_harv = " and a working paper (in other words, not yet reviewed by other scientists) developed by "
    #Chowkwanyun
    temp_pre_nejm = "A recent Perspectives paper in the "
    temp_post_nejm = " authored by Dr. Merlin Chowkwanyun and Dr. Adolph L. Reed, Jr. provides context regarding COVID-19 disparities."
    all_tags = list(intro, tags$br(), tags$br(), 
                    temp_pre_nyt, nyt_url, 
                    temp_pre_harv, harv_paper_url, 
                    " from the ", hsph_url, tags$br(), tags$br(),
                    temp_pre_nejm, nejm_url, temp_post_nejm)
    tagList(all_tags)
  })
  hire_url <- a("Columbia University Medical Center.",
                href = "https://www.genmed.columbia.edu/research/research-centers-and-programs/columbia-outcomes-research-and-decision-analysis-corda-1")
  
  res_gate_url <- a("ResearchGate",
                    href = "https://www.researchgate.net/profile/Elisabeth_Silver2")
  output$about_me <- renderUI({
    intro = paste("Elisabeth Silver developed this application. She graduated from the University of Michigan in 2018 with a Bachelor's of Science,",
                  " and has since been working as a Research Analyst at ",
                  sep = '')
    rg = "To read some of the developer's peer-reviewed research, please visit her profile on "
    contact = "For inquiries, please contact Elisabeth via email: silver.elisabeth@gmail.com"
    all_tags = list(intro, hire_url, tags$br(),
                    rg, res_gate_url, tags$br(), tags$br(),
                    contact, tags$br())
  })
  
}

shinyApp(ui, server)