
#Where new data generated by code is
new_data <- './data/'
#Where figures are stored
figs <- './figures/'

#NOTE: this needs to be pulled from https://github.com/nychealth/coronavirus-data
nyc_data <- "./coronavirus-data/"
geo_data <- paste(nyc_data, "Geography-resources/", sep = '')

choro_fname <- paste('choropleth_inputs_',  "2020-06-01", sep = '')
choro_fname <- paste(choro_fname, '.csv', sep = '')