
#Where new data generated by code is
new_data <- './data/'
#Where figures are stored
figs <- './figures/'
all_time_data <- './data_over_time/'

#NOTE: this needs to be pulled from https://github.com/nychealth/coronavirus-data
nyc_data <- "./coronavirus-data/"
geo_data <- paste(nyc_data, "Geography-resources/", sep = '')

merged_fname <- 'covid_data_w_census.csv'

choro_fname <- 'choropleth_inputs.csv'