
#Where new data generated by code is
new_data = './data/'
#Where figures are stored
figs = './figures/'

#NOTE: this needs to be pulled from https://github.com/nychealth/coronavirus-data
nyc_data = paste(new_data, "coronavirus-data/", sep = '')
geo_data = paste(nyc_data, "Geography-resources/", sep = '')

