library(choroplethrZip)
library(choroplethr)
library(dplyr)
library(ggplot2)
library(sf)
library(stats)
library(Hmisc)
library(ggcorrplot)

#######################################
# Set path and global variables
#######################################

setwd("~/Documents/covid_nyc_map/")
source('./src/data_paths.R')

SAVE_FIGS = TRUE
vars = read.csv(paste(new_data, 'census_variables.csv', sep = ''),
                    stringsAsFactors = F)
merged = read.csv(paste(new_data, 'covid_data_w_census.csv', sep= ''),
                  stringsAsFactors = F)

merged$ZCTA = as.character(merged$ZCTA)

nyc_fips = c('36005', '36047', '36061', '36081', '36085')
plot_cols = c('median_income', 'percent_white', 'percent_black',
              'percent_hispanic_latino', 'percent_uninsured',
              'percent_receiving_public_assistance',
              'high_school_completion', 'percent_in_mgmt_art_sci',
              'poverty_rate', 'percent_private_health_insurance',
              'percent_unemployed')

new_vars = vars %>% 
  filter(variable_label %in% plot_cols)
pretty_cols = as.vector(new_vars$pretty_label)
plot_cols = as.vector(new_vars$variable_label)

# Create a df that can be plotted with ggplot2
# Relies on choropleth package to build the plotting dataframe
generate_choro_df <- function(temp_df, full_df){
  choro = ZipChoropleth$new(temp_df)
  choro$set_zoom_zip(state_zoom = 'new york',county_zoom=nyc_fips, msa_zoom=NULL, zip_zoom=NULL)
  choro$prepare_map()
  choro_df = choro$choropleth.df
  choro_df['ZCTA'] = as.character(choro_df$ZCTA5CE10)
  choro_df = choro_df %>% 
    filter(ZCTA %in% full_df$ZCTA)
  choro_df = left_join(choro_df, full_df, by = 'ZCTA')
  return(choro_df)
}

# Uses dataframe generated by generate_choro_df to plot desired outcomes
build_choropleth <- function(choro_df, var_label, pretty_label,
                             min_color = 'lightgrey', max_color = 'darkblue'){
  p = ggplot() + 
    geom_polygon(data=choro_df %>% filter(!is.na(.data[[var_label]])), 
                 aes(x=long, y=lat, group=group, fill = .data[[var_label]])) +
    scale_fill_gradient(low = min_color, high = max_color, 
                        guide = 
                          guide_colorbar(
                            title = pretty_label,order = 1,reverse = F
                          )
    )+
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank()) +
    labs(title=sprintf('%s by zip code', pretty_label),
         x ="", y = "")
  
  return(p)
}

#Test zip code choropleths
temp_acs = merged %>% 
  select(region = ZCTA,
         value = median_income)

choro_inputs = generate_choro_df(temp_acs, merged)

write.csv(choro_inputs,paste(new_data, 'choropleth_inputs.csv', sep = ''))

temp_chor = read.csv(paste(new_data, 'choropleth_inputs.csv', sep = ''),
                        stringsAsFactors = FALSE)

test_plot = build_choropleth(temp_chor, 'median_income', 'Median Income')
print(test_plot)



#Create correlation matrix
keep_covid = c('PERCENT_POSITIVE', 'COVID_CASE_RATE', 'COVID_DEATH_RATE')

vars = vars %>% 
  filter(variable_label %in% as.vector(colnames(merged)))

keep_covid = append(keep_covid, as.vector(vars$variable_label))
keep_covid = append(keep_covid, 'crowding')
corr_df = merged %>% 
  select(all_of(keep_covid)) 

#save the merged data frame
#write.csv(corr_df, 'merged_covid_census_data.csv')
#Get correlation matrix
merged.rcorr = rcorr(as.matrix(corr_df))
merged.coeff = merged.rcorr$r
merged.p = merged.rcorr$P

merged.coeff = as.data.frame(merged.coeff) %>% 
  select(c(PERCENT_POSITIVE))
merged.p = as.data.frame(merged.p) %>% 
  select(c(PERCENT_POSITIVE))
#Make correlation dataframe
all_cors = cbind(merged.coeff, merged.p)
colnames(all_cors) = c('r', 'p')
all_cors['variable'] = rownames(all_cors)
rownames(all_cors) = 1:nrow(all_cors)
#Filter to just significant correlations
#Sort by absolute correlation strength
sig_corrs = all_cors %>% 
  filter(p < 0.05) %>% 
  arrange(desc(abs(r)))
#Add % positive to dataframe
keep_plot = append('PERCENT_POSITIVE', as.vector(sig_corrs$variable))
new_corr_df = corr_df %>% 
  select(all_of(keep_plot))

#create correlation matrix with only significant correlations
new_merged.rcorr = rcorr(as.matrix(new_corr_df))
new_merged.coeff = new_merged.rcorr$r
#plot the new correlation matrix
if(SAVE_FIGS == T){
  png(paste(figs, "cov_correlations.png", sep = ''), width = 13, 
      height = 13, units = "in", res = 250)
  ggcorrplot(new_merged.coeff, type = 'lower')
  dev.off()
}else{
  ggcorrplot(new_merged.coeff, type = 'lower')
}

# OLD 
# 
# 
# 
# 
# png(paste(figs, "choropleth_median_income.png", sep = ''), width = 13, 
#     height = 13, units = "in", res = 250)
# choro$set_zoom_zip(state_zoom = 'new york',county_zoom=nyc_fips, msa_zoom=NULL, zip_zoom=NULL)
# choro$title = "Median income"
# choro$prepare_map()
# choro$ggplot_scale = scale_fill_brewer(name="Median income", palette=2, drop=TRUE)
# choro$render()
# dev.off()
# 
# temp_acs = merged %>% 
#   select(region = ZCTA,
#          value = plot_cols[2])
# figname = sprintf("%s_choropleth.png", plot_cols[2])
# png(paste(figs, figname, sep = ''), width = 13, 
#     height = 13, units = "in", res = 250)
# #Test zip code choropleths
# choro = ZipChoropleth$new(temp_acs)
# choro$set_zoom_zip(state_zoom = 'new york',county_zoom=nyc_fips, msa_zoom=NULL, zip_zoom=NULL)
# choro$title = pretty_cols[2]
# choro$prepare_map()
# choro$ggplot_scale = scale_fill_brewer(name=pretty_cols[2], palette=2, drop=TRUE)
# choro$render_helper(theme = )
# choro$render()
# dev.off()
# 
# 
# 
# # library(rgdal)
# # 
# # nyc_neighborhoods <- readOGR(paste(new_data, 'nyc_zip_code_tabulation_areas.geojson',
# #                                    sep = ''), verbose = T)
# # library(broom)
# # nyc_neighborhoods_df <- tidy(nyc_neighborhoods)
# choro_list = list()
# for(i in 1:3){
#   test_choro = build_choropleth(merged, 
#                                 plot_cols[i], new_vars[i])
#   choro_list = append(choro_list, test_choro)
# }
# 
# 
# temp_cov = merged %>% 
#   select(value = PERCENT_POSITIVE,
#          region = ZCTA)
# 
# choro1 = choroplethrZip::ZipChoropleth$new(temp_cov)
# choro1$set_zoom_zip(state_zoom = 'new york',county_zoom=nyc_fips, msa_zoom=NULL, 
#                     zip_zoom=NULL)
# 
# choro1$title = 'Percent Positive'
# choro1$prepare_map()
# choro1$ggplot_scale = scale_fill_brewer(name='Percent positive', palette=2, drop=TRUE)
# choro1$render()


